#!/bin/bash

set -e

test -f "$1" || ( echo "Specify .yml file as first argument" >&2 ; exit 1 )

sudo add-apt-repository -y ppa:git-core/ppa
sudo add-apt-repository -y ppa:ansible/ansible
sudo apt-get -qq update
sudo apt-get install -qqy ansible

ansible-galaxy install dotstrap.fzf
if [[ "$1" == "server.yml" ]]; then
  ansible-galaxy install jdauphant.nginx
  ansible-galaxy install geerlingguy.certbot
fi

sudo ansible-playbook $1 -i inventory
