#!/bin/bash
# vim:ts=2:sw=2:et

set -e
set -u

test -f "$1" || ( echo "Specify .yml file as first argument" >&2 ; exit 1 )

if grep -q -i debian /etc/os-release; then
  echo Detected Debian

  # docker-ce
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo apt-key fingerprint 0EBFCD88
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
elif grep -q -i ubuntu /etc/os-release; then
  echo Detected Ubuntu

  # docker-ce
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo apt-key fingerprint 0EBFCD88
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
fi

sudo apt-get -qq update
sudo apt-get install -qqy ansible

if [[ "$1" == "server.yml" ]]; then
  ansible-galaxy install jdauphant.nginx
  ansible-galaxy install geerlingguy.certbot
fi

echo ansible-playbook $1
ansible-playbook $1 -i inventory
