---
- hosts: all
  tasks:
    - apt: update_cache=yes cache_valid_time=3600

    # shell environment
    - apt:
        pkg:
          - asciinema
          - autojump
          - clusterssh
          - mosh
          - ncdu
          - parallel
          - pwgen
          - qalc
          - ranger
          - renameutils
          - sshfs
          - tilix
          - tree
          - tmux
          - tmux-plugin-manager
          - ttyrec
          - vim-gtk
          - wajig
          - zsh

    # ripgrep
    - apt: deb=https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb

    # diagnostics
    - apt:
        pkg:
          - atop
          - bmon
          - bonnie++
          - glances
          - htop
          - iftop
          - iotop
          - mbuffer
          - netcat
          - nethogs
          - nicstat
          - nmap
          - pydf
          - slurm
          - sysstat
          - tcptraceroute
          - traceroute
          - wipe

    # working with files
    - apt:
        pkg:
          - aria2
          - cryptsetup
          - curl
          - httpie
          - lbzip2
          - lftp
          - p7zip-full
          - pigz
          - unzip
          - wget
          - zip

    # media
    - apt:
        pkg:
          - imagemagick
          - exiftool
          - mediainfo
          - mpv

    # coding
    - apt:
        pkg:
          - cloc
          - docker.io
          - dos2unix
          - git
          - gitk
          - ipython
          - ipython3
          - jq
          - python-dev
          - python-pip
          - python3-dev
          - python3-pip
          - rlwrap
          - tig
          - weechat
          - weechat-plugins
          - xmlstarlet
          - znc

    # firewall
    - ufw:
        state: enabled
    - ufw:
        logging: off
    - ufw:
        rule: limit
        port: ssh
        proto: tcp
    - ufw:
        rule: allow
        port: ssh

    # services
    - apt:
        pkg:
          - openssh-server

    # latest version of everything
    - name: "apt upgrade"
      apt: upgrade=yes

    # dot-files
    - file:
        path: "{{ ansible_env.HOME + '/.ssh' }}"
        state: directory
        mode: 0700
    - blockinfile:
        block: "{{ lookup('file', 'dotfiles/' + item.0) }}"
        dest: "{{ ansible_env.HOME + '/' + item.1 }}"
        insertbefore: BOF
        create: yes
      with_together:
        - "{{ ['_zshrc', '_inputrc', '_ssh_config', '_vimrc', '_gitconfig', '_tmux.conf'] }}"
        - "{{ ['.zshrc', '.inputrc', '.ssh/config', '.vimrc', '.gitconfig', '.tmux.conf'] }}"

    # useful scripts
    - file:
        path: "{{ansible_env.HOME}}/.local/bin/"
        state: directory
    - name: tmux-cssh
      copy:
        src: tmux-cssh
        dest: "{{ansible_env.HOME}}/.local/bin/tmux-cssh"
        mode: u+rx,g+rx,o+rx
    - get_url:
        url: "https://git.io/antigen"
        dest: "{{ansible_env.HOME}}/.local/bin/antigen.zsh"

    # fix ownership of paths and files, because ansible ran under sudo
    - file:
        name: "{{ansible_env.HOME}}"
        owner: agfung
        group: agfung
        recurse: yes
