# vim:ts=2:sw=2:et
---
- hosts: all
  tasks:
    - name: "apt - update"
      become: true
      apt: update_cache=yes cache_valid_time=3600

    - name: "apt - shell tools"
      become: true
      apt:
        pkg:
          - asciinema
          - autojump
          - clusterssh
          - mosh
          - ncdu
          - parallel
          - pwgen
          - qalc
          - ranger
          - renameutils
          - sshfs
          - tilix
          - tree
          - tmux
          - tmux-plugin-manager
          - ttyrec
          - vim-gtk
          - wajig
          - zsh

    - name: "apt - ripgrep"
      become: true
      apt: deb=https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb

    - name: "fzf"
      git:
        repo: 'https://github.com/junegunn/fzf.git'
        dest: "{{ ansible_env.HOME }}/.fzf"
    - shell: "{{ ansible_env.HOME }}/.fzf/install"

    - name: "apt - diagnostic tools"
      become: true
      apt:
        pkg:
          - bmon
          - bonnie++
          - glances
          - htop
          - iftop
          - iotop
          - mbuffer
          - netcat
          - nethogs
          - nicstat
          - nmap
          - pydf
          - slurm
          - sysstat
          - tcptraceroute
          - traceroute
          - wipe

    - name: "apt - file tools"
      become: true
      apt:
        pkg:
          - aria2
          - cryptsetup
          - curl
          - httpie
          - lbzip2
          - lftp
          - p7zip-full
          - pigz
          - unzip
          - wget
          - zip

    - name: "apt - media tools"
      become: true
      apt:
        pkg:
          - imagemagick
          - exiftool
          - mediainfo
          - mpv

    - name: "apt - development tools"
      become: true
      apt:
        pkg:
          - cloc
          - docker-ce
          - docker-compose
          - dos2unix
          - git
          - gitk
          - ipython
          - ipython3
          - jq
          - python-dev
          - python-pip
          - python3-dev
          - python3-pip
          - rlwrap
          - tig
          - weechat
          - weechat-plugins
          - xmlstarlet
          - znc

    # firewall
    - name: "ufw"
      become: true
      block:
      - ufw:
          state: enabled
      - ufw:
          logging: off
      - ufw:
          rule: limit
          port: ssh
          proto: tcp
      - ufw:
          rule: allow
          port: ssh
      - ufw:
          rule: allow
          port: 60000:60006
          proto: udp

    - name: "apt - services"
      become: true
      apt:
        pkg:
          - openssh-server

    - name: "apt upgrade"
      become: true
      apt: upgrade=yes

    # dot-files
    - file:
        path: "{{ ansible_env.HOME + '/.ssh' }}"
        state: directory
        mode: 0700
    - blockinfile:
        block: "{{ lookup('file', 'dotfiles/' + item.0) }}"
        dest: "{{ ansible_env.HOME + '/' + item.1 }}"
        insertbefore: BOF
        create: yes
      with_together:
        - "{{ ['_zshrc', '_inputrc', '_ssh_config', '_gitconfig', '_tmux.conf'] }}"
        - "{{ ['.zshrc', '.inputrc', '.ssh/config', '.gitconfig', '.tmux.conf'] }}"
    - blockinfile:
        block: "{{ lookup('file', 'dotfiles/_vimrc') }}"
        dest: "{{ ansible_env.HOME + '/.vimrc' }}"
        insertbefore: BOF
        create: yes
        marker: "\" {mark} ANSIBLE MANAGED BLOCK"

    # useful scripts
    - file:
        path: "{{ansible_env.HOME}}/.local/bin/"
        state: directory
    - name: tmux-cssh
      copy:
        src: tmux-cssh
        dest: "{{ansible_env.HOME}}/.local/bin/tmux-cssh"
        mode: u+rx,g+rx,o+rx
    - name: antigen
      get_url:
        url: "https://git.io/antigen"
        dest: "{{ansible_env.HOME}}/.local/bin/antigen.zsh"
