set nocompatible | filetype indent plugin on | syn on

set visualbell
set lazyredraw
set history=9999
set undolevels=9999
set nobackup
set nowritebackup
set noswapfile

set expandtab
set sw=2
set ts=2
set sts=2

set hlsearch
set nojoinspaces
set tw=200
set nowrap

" Automatic installaion of vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !mkdir -p ~/.vim/autoload
  silent !curl -fLo ~/.vim/autoload/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin('~/.vim/plugged')
Plug 'farmergreg/vim-lastplace'
Plug 'ntpeters/vim-better-whitespace'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()
